### PR TITLE
Windows compatibility: replace ifaces crate with get_if_addrs

### PR DESCRIPTION
**Pull request by GeorgeHahn**
This PR adds Windows compatibility. The `ifaces` crate is replaced with the `get_if_addrs` crate, which supplies the required functionality and is cross platform.

UDP socket creation is moved to an os-specific function. There should likely be a macOS specialization as well, but I do not own a mac to test on. Reference: https://github.com/rust-lang-nursery/net2-rs/issues/46

### CODE REVIEW

**Comment by dylanmckay** [comment]
Nice patch, I always wanted to replace the `ifaces` dependency due to its staleness but I couldn't find a good replacement. `get_if_addrs` looks nice.

**Comment by dylanmckay** [comment]
Doesn't change the public API either, neat.

**Comment by dylanmckay** [comment]
I'll push a new minor version to crates.io when I've come back from grocery shopping

**Comment by GeorgeHahn** [comment]
Ping :wink:

**Comment by dylanmckay** [comment]
Whoops!

Published [0.3.1](https://crates.io/crates/mdns/0.3.1) in 13f20a5e126b7361be69acc3bcff02bc23286015.

**Pull request merged**
